// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZcVr9nFSxBwDm0Js6bihzzcIO2HBo-0k',
    appId: '1:198623049011:web:cd29b029a26115b84a3a46',
    messagingSenderId: '198623049011',
    projectId: 'shop-app-a2b60',
    authDomain: 'shop-app-a2b60.firebaseapp.com',
    storageBucket: 'shop-app-a2b60.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALT61MqTynDHIOtELvS9RHB-_47Wskf6s',
    appId: '1:198623049011:android:accd7fee5f9b51064a3a46',
    messagingSenderId: '198623049011',
    projectId: 'shop-app-a2b60',
    storageBucket: 'shop-app-a2b60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4R7M94vnoQ7Rn2D_FTBu2mT6jIAAKJvE',
    appId: '1:198623049011:ios:2d42bad5a23363f44a3a46',
    messagingSenderId: '198623049011',
    projectId: 'shop-app-a2b60',
    storageBucket: 'shop-app-a2b60.appspot.com',
    iosClientId: '198623049011-3i1mptsjihrhem9oe1dco3v19m21f2gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.asroo',
  );
}
